version: "3.9"
services:
  mysql:
    restart: always
    container_name: "mysql-container-yml"
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=0528
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=0528